Algoritmo "variáveis"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Udemy - Cleison Melo
// Descrição   : Testar Variáveis
// Autor(a)    : Joyce
// Data atual  : 26/05/2020
Var
// Seção de Declarações das variáveis
 nota : inteiro,
 nota2 : real ,
 nome: caractere  ,
 aprovado : logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...



Fimalgoritmo